Networking dio
dmitry-rachko-idf/jenkins pull request #5
Opened 2022-03-21 13:19 UTC by dmitry-rachko-idf

2022-03-21 14:03 UTC, andrei-lastochkin-idf approved these changes

2022-03-21 14:03 UTC, andrei-lastochkin-idf commented on packages/domain/lib/model/list_job_model.dart
> +class ListJobModel {
naming, try something like JobListCache

2022-03-21 14:03 UTC, andrei-lastochkin-idf commented on packages/domain/lib/usecase/get_job_list_usecase.dart
> +      final a = _repository
naming

2022-03-21 14:03 UTC, andrei-lastochkin-idf commented on packages/domain/lib/usecase/get_job_list_usecase.dart
> +  late ListJobModel _jobList;
-//-

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf requested changes

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/network_repository.dart
> +            AuthorizationException("login.invalid", "password.invalid"),
same as with paths - separate errors

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/di/domain_injector.dart
> +  _initCashModule();
cash -> cache

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/di/domain_injector.dart
> +        GetIt.I.get<INetworkRepository>(), GetIt.I.get<JobListCacheModel>()),
formatting. add comma before the last bracket

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/di/domain_injector.dart
> +        GetIt.I.get<INetworkRepository>(), GetIt.I.get<JobListCacheModel>()),
the same

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/di/domain_injector.dart
> +void _initCashModule() {
-//-

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/api_registration_response.dart
>  class ApiRegistrationResponse implements RegistrationResponse {
RegistrationResponse -> LoginResponse

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/login_step_fields.dart
>  import 'package:domain/model/api_base_json_request.dart';
why do u need this model?

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/registration_response.dart
>  abstract class RegistrationResponse {
Registration -> Login

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/repository/network_repository.dart
> +  Future<ApiRegistrationResponse?> sendRegistration(String auth);
-//-

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_job_list_usecase.dart
> +  late JobListCacheModel _jobList;
why did u do it late but not final as u did with repository?

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/send_registration_usecase.dart
>  class SendRegistrationStepUseCase
-//-

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/send_registration_usecase.dart
> +  SendRegistrationStepUseCase(this._repository, this._jobList);
-//-

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_job_list_usecase.dart
> +    final prefs = await SharedPreferences.getInstance();
provide preferences via di

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/send_registration_usecase.dart
> +    final prefs = await SharedPreferences.getInstance();
-//-

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/domain/pubspec.yaml
> +  shared_preferences: ^2.0.13
preferences should be at the data layer. and if u need to access them in domain do it via repository as u do with network

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/home_page/home_bloc.dart
> +  final bool _isLoading = false;
isLoading shouldn't be final. it can change it's value

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/home_page/home_page.dart
> +      );
formatting

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/home_page/home_page.dart
> +              itemCount: screenData.job!.length,
! -> ?

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/login_page/login_data.dart
> +      : false;
what is this method used for?

2022-03-21 16:17 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/login_page/login_page.dart
> +                  },
why async?

2022-03-21 16:51 UTC, dmitry-rachko-idf commented on packages/domain/lib/di/domain_injector.dart
> +  _initCashModule();
fixed everywhere, just forgot here(

2022-03-22 09:30 UTC, dmitry-rachko-idf commented on packages/presentation/lib/screens/login_page/login_data.dart
> +      : false;
this is a kind of check, if the login and password are empty, then when you click on the login button, the login will return an error, this is temporary until there is no normal validation

2022-03-23 12:12 UTC, dmitry-rachko-idf commented on packages/data/lib/repository/network_repository.dart
> +            AuthorizationException("login.invalid", "password.invalid"),
but AuthorizationException is a separate class

2022-03-29 10:19 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/path_repository.dart
> +class ApiPathRepository {
naming - it's not a repository. call it ApiPaths/Endpoints or smth similar to these

2022-03-29 10:19 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/path_repository.dart
> +  final LOGIN_PATH = 'api/json?pretty=true';
in the case of constants, u can make them static. it will help u to avoid creating objects. but it's only for case with constants

2022-03-29 10:19 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/network_repository.dart
> +            AuthorizationException("login.invalid", "password.invalid"),
i mean move login.invalid and password.invalid to constants in separate file/class

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf approved these changes

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/di/data_injector.dart
> +import 'package:domain/repository/shared_preferences_repository.dart';
formatting

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/shared_preferences_repository.dart
> +    final auth = await _preferences.getString('auth');
auth - to separate constant

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/get_job_list_usecase.dart
> +      this._repository, this._jobList, this._sharedPreferencesRepo);
comma

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/login_usecase.dart
> +    dynamic cache = await _repository.login('Basic ' + auth);
_repository.login returns ApiLoginResponse, so no need in specifying dynamic type here. use it like

ApiLoginResponse cache or final cache

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/usecase/login_usecase.dart
>          base64.encode(utf8.encode(header.login! + ':' + header.password!));
! -> ?

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/home_page/home_page.dart
> +            itemCount: screenData.job!.length,
! -> ?

2022-03-29 10:25 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/login_page/login_page.dart
> +                } else {
what is the error state? seems that u shouldn't handle it separately

2022-03-29 11:21 UTC, merged